### ISSUE TITLE
hull is what, how to installl?

### ISSUE THREAD

**Issue by PhilChina** [potpov/New-Maxillo-Dataset-Segmentation#1]
from hull.voxelize.voxelize import voxelize

**Comment by potpov** [comment]
Dear Larry, 
Thank you for your comment. The Voxelizer comes from an [external github project](https://github.com/p-hofmann/PyVoxelizer) that we slightly edited for our purposes.

However, I just pushed the missing folder to the Repo: #[b51bc98](https://github.com/potpov/New-Maxillo-Dataset-Segmentation/commit/b51bc985ba33a3c97744c719c13e67a5759252f1). You should be able to run that line now.
